# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: "registry.access.redhat.com/ubi8/ubi"
  tag: latest
command: 'echo "hello world"'
